### ISSUE TITLE
Error loading `lego-sales` Shiny App

### ISSUE THREAD

**Issue by luciorq** [rstudio-education/instructor-training#2]
Hello,

I'm just reporting that I couldn't load [`lego-sales` Shiny App](https://gallery.shinyapps.io/lego-sales/) used on [*building interactive tutorials in R*](https://rstudio-education.github.io/instructor-training/slides/tutorial.html).

It is reporting an error, as seen on the following screenshot, taken on October 24th, 2020.

<https://gallery.shinyapps.io/lego-sales/>

![image](https://user-images.githubusercontent.com/22479186/97091195-80230a80-1610-11eb-9271-a8509f463a35.png)

Thanks for the amazing effort on this content.

**Comment by luciorq** [comment]
I explored a bit further and found that is probably related to the file <https://raw.githubusercontent.com/ids-s1-20/data/master/HW04/lego_sales.csv> that is accessed by the link shortener <https://rb.gy/shkc8g>  don't exist anymore.

I found that probably the same data set exists in the [rstudio-education/dsbox](https://github.com/rstudio-education/dsbox) repo and can be accessed  via <https://raw.githubusercontent.com/rstudio-education/dsbox/master/data-raw/lego-sales/lego-sales.csv>

and here <https://raw.githubusercontent.com/rstudio-education/instructor-training/master/examples/lego-sales/data/lego_sales.csv>

**Comment by mine-cetinkaya-rundel** [comment]
As mentioned in the linked issues, fixed now. Thanks!
